# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Serre2', [dirname(__file__)])
        except ImportError:
            import _Serre2
            return _Serre2
        if fp is not None:
            try:
                _mod = imp.load_module('_Serre2', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Serre2 = swig_import_helper()
    del swig_import_helper
else:
    import _Serre2
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def mallocPy(*args):
  return _Serre2.mallocPy(*args)
mallocPy = _Serre2.mallocPy

def writetomem(*args):
  return _Serre2.writetomem(*args)
writetomem = _Serre2.writetomem

def readfrommem(*args):
  return _Serre2.readfrommem(*args)
readfrommem = _Serre2.readfrommem

def deallocPy(*args):
  return _Serre2.deallocPy(*args)
deallocPy = _Serre2.deallocPy

def evolvewrap(*args):
  return _Serre2.evolvewrap(*args)
evolvewrap = _Serre2.evolvewrap

def getufromG(*args):
  return _Serre2.getufromG(*args)
getufromG = _Serre2.getufromG

def minmod(*args):
  return _Serre2.minmod(*args)
minmod = _Serre2.minmod

def GNall(*args):
  return _Serre2.GNall(*args)
GNall = _Serre2.GNall

def conc(*args):
  return _Serre2.conc(*args)
conc = _Serre2.conc

def MyCorrectionallcells(*args):
  return _Serre2.MyCorrectionallcells(*args)
MyCorrectionallcells = _Serre2.MyCorrectionallcells

def MyCorrectionalltimes(*args):
  return _Serre2.MyCorrectionalltimes(*args)
MyCorrectionalltimes = _Serre2.MyCorrectionalltimes

def HankEnergyall(*args):
  return _Serre2.HankEnergyall(*args)
HankEnergyall = _Serre2.HankEnergyall
# This file is compatible with both classic and new-style classes.


