# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Serre2GR', [dirname(__file__)])
        except ImportError:
            import _Serre2GR
            return _Serre2GR
        if fp is not None:
            try:
                _mod = imp.load_module('_Serre2GR', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Serre2GR = swig_import_helper()
    del swig_import_helper
else:
    import _Serre2GR
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def mallocPy(n):
    return _Serre2GR.mallocPy(n)
mallocPy = _Serre2GR.mallocPy

def writetomem(x, i, f):
    return _Serre2GR.writetomem(x, i, f)
writetomem = _Serre2GR.writetomem

def readfrommem(x, i):
    return _Serre2GR.readfrommem(x, i)
readfrommem = _Serre2GR.readfrommem

def deallocPy(x):
    return _Serre2GR.deallocPy(x)
deallocPy = _Serre2GR.deallocPy

def evolvewrap(u, h, pubc, h0, h1, u0, u1, g, dx, dt, nBC, n, nBCs):
    return _Serre2GR.evolvewrap(u, h, pubc, h0, h1, u0, u1, g, dx, dt, nBC, n, nBCs)
evolvewrap = _Serre2GR.evolvewrap

def HankEnergyall(x, h, u, g, n, nBC, dx):
    return _Serre2GR.HankEnergyall(x, h, u, g, n, nBC, dx)
HankEnergyall = _Serre2GR.HankEnergyall

def conc(a, b, c, n, m, k, d):
    return _Serre2GR.conc(a, b, c, n, m, k, d)
conc = _Serre2GR.conc
# This file is compatible with both classic and new-style classes.


